### ISSUE TITLE
Errno::EADDRNOTAVAIL: Cannot assign requested address - connect(2) for [::1]:7687

### ISSUE THREAD

**Issue by jasonfine** [ahmad-elassuty/rails_graph#7]
Hi - trying to use this in an existing docker-based app, i've followed the docs and referenced the compose file in your example app https://github.com/ahmad-elassuty/rails_graph_example, but am seeing the error when running

`docker-compose app bundle exec rails rails_graph:export:neo4j -- -u neo4j -p anypass123 -h neo4j://localhost:7687`

```
rails aborted!
Errno::EADDRNOTAVAIL: Cannot assign requested address - connect(2) for [::1]:7687

**Comment by ahmad-elassuty** [comment]
Hi @jasonfine 👋 It seems that your app cannot connect to the Neo4j database. I would suggest you first verify that the Neo4j container is running and the database has started. If the database container is running, then you should be able to access Neo4j Browser UI on http://localhost:7474/ , let me know how it goes!

**Comment by jasonfine** [comment]
The issue was trying to use localhost in the generator command, Docker wasn't liking that. What ended up working was using `neo4j://graph_db` instead of `neo4j://localhost:7687`
